write() argument must be str, not Historywrite()
argument must be str, not History[Errno 32] Broken pipeA target array with shape (39965, 1) was passed for an output of shape (None, 2, 1) while using as loss `mean_squared_error`. This loss expects targets to have the same shape as the output.





A target array with shape (39965, 1) was passed for an output of shape (None, 2, 1) while using as loss `mean_squared_error`.
This loss expects targets to have the same shape as the output.
[Errno 2] No such file or directory: 'results/Auto_Looping/Round1.1/High.txt'
[Errno 2] No such file or directory: 'results/Auto_Looping/Round1.1/Low.txt'
[Errno 2] No such file or directory: 'results/Auto_Looping/Round1.1/Volumes.txt'
[Errno 2] No such file or directory: 'results/Auto_Looping/Round1.1/RSI.txt'
[Errno 2] No such file or directory: 'results/Auto_Looping/Round1.1/ADL.txt'
[Errno 2] No such file or directory: 'results/Auto_Looping/Round1.1/ADL_slope.txt'
[Errno 2] No such file or directory: 'results/Auto_Looping/Round1.1/OBV.txt'
[Errno 2] No such file or directory: 'results/Auto_Looping/Round1.1/OBV_slope.txt'
Type of `metrics` argument not understood. Expected a list or dictionary, found: mape
Type of `metrics` argument not understood. Expected a list or dictionary, found: mape
Type of `metrics` argument not understood. Expected a list or dictionary, found: mape
Input 0 is incompatible with layer lstm_9: expected ndim=3, found ndim=2
Input 0 is incompatible with layer lstm_18: expected ndim=3, found ndim=2
Input 0 is incompatible with layer lstm_27: expected ndim=3, found ndim=2
Input 0 is incompatible with layer lstm_36: expected ndim=3, found ndim=2
Input 0 is incompatible with layer lstm_45: expected ndim=3, found ndim=2
Input 0 is incompatible with layer lstm_54: expected ndim=3, found ndim=2
Input 0 is incompatible with layer lstm_63: expected ndim=3, found ndim=2
Input 0 is incompatible with layer lstm_72: expected ndim=3, found ndim=2
Must specify `validation_steps` to perform validation when doing step-wise training.
Must specify `validation_steps` to perform validation when doing step-wise training.
Must specify `validation_steps` to perform validation when doing step-wise training.
Must specify `validation_steps` to perform validation when doing step-wise training.
Must specify `validation_steps` to perform validation when doing step-wise training.
The number of samples 58323 is not divisible by steps 3000. Please change the number of steps to a value that can consume all the samples
The number of samples 58323 is not divisible by steps 3000. Please change the number of steps to a value that can consume all the samples
The number of samples 58323 is not divisible by steps 3000. Please change the number of steps to a value that can consume all the samples
The number of samples 58323 is not divisible by steps 3000. Please change the number of steps to a value that can consume all the samples
The number of samples 58323 is not divisible by steps 3000. Please change the number of steps to a value that can consume all the samples
The number of samples 58323 is not divisible by steps 3000. Please change the number of steps to a value that can consume all the samples
The number of samples 58323 is not divisible by steps 3000. Please change the number of steps to a value that can consume all the samples
'Sequential' object has no attribute 'score'
'NoneType' object has no attribute 'to_csv'
'NoneType' object has no attribute 'to_csv'
'list' object has no attribute 'to_csv'
'list' object has no attribute 'to_csv'
write() argument must be str, not list
[Errno 2] No such file or directory: 'results/New_Model/1/None/Low_Prices_vs_Prices/Model.txt'
[Errno 17] File exists: '/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/New_Model/1/Low_Prices_vs_Prices'
[Errno 2] No such file or directory: '/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictorresults/New_Model/1/Low_Prices_vs_Prices'
[Errno 2] No such file or directory: 'results/New_Model/1/None/Model.txt'
write() argument must be str, not numpy.ndarray
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/0/['High']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/1/['Low']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/2/['Volumes']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/3/['RSI']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/4/['ADL']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/5/['OBV']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/6/['ADL_slope']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/7/['OBV_slope']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/8/['High', 'Low']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/9/['High', 'Volumes']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/10/['High', 'RSI']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/11/['High', 'ADL']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/12/['High', 'OBV']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/13/['High', 'ADL_slope']_vs_Prices"
[Errno 2] No such file or directory: "/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Final/14/['High', 'OBV_slope']_vs_Prices"
Error when checking input: expected lstm_input to have 3 dimensions, but got array with shape (48604, 1)
Error when checking input: expected lstm_6_input to have 3 dimensions, but got array with shape (48604, 1)
Error when checking input: expected lstm_12_input to have 3 dimensions, but got array with shape (48604, 1)
Error when checking input: expected lstm_18_input to have 3 dimensions, but got array with shape (48604, 1)
Error when checking input: expected lstm_24_input to have 3 dimensions, but got array with shape (48604, 1)
Error when checking input: expected lstm_30_input to have 3 dimensions, but got array with shape (48604, 1)
Error when checking input: expected lstm_36_input to have 3 dimensions, but got array with shape (48604, 1)
[Errno 2] No such file or directory: '/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Slim/High_Low_vs_Prices'
If a RNN is stateful, it needs to know its batch size. Specify the batch size of your input tensors: 
- If using a Sequential model, specify the batch size by passing a `batch_input_shape` argument to your first layer.
- If using the functional API, specify the batch size by passing a `batch_shape` argument to your Input layer.
[Errno 17] File exists: '/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Slim_Model/High_Low_vs_Prices'
cannot reshape array of size 118346 into shape (16,2,59173)
[Errno 17] File exists: '/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Slim_Model/High_Low_vs_Prices'
[Errno 17] File exists: '/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/Slim_Model/High_Low_vs_Prices'
cannot reshape array of size 118346 into shape (2,59173,16)
add() got an unexpected keyword argument 'input_shape'
The added layer must be an instance of class Layer. Found: <keras.layers.recurrent.LSTM object at 0x1476eb390>
Unknown metric function:rmse
The `batch_size` argument value 16 is incompatible with the specified batch size of your Input Layer: 59173
Error when checking input: expected lstm_input to have shape (59173, 2) but got array with shape (59173, 1)
Error when checking input: expected lstm_input to have shape (59173, 2) but got array with shape (59173, 1)
Error when checking input: expected lstm_input to have shape (59173, 2) but got array with shape (2, 1)
'int' object is not iterable
The `batch_size` argument value 16 is incompatible with the specified batch size of your Input Layer: 59173
Error when checking input: expected lstm_input to have shape (59173, 2) but got array with shape (59173, 1)
Error when checking input: expected lstm_input to have shape (59173, 2) but got array with shape (59173, 1)
Error when checking input: expected lstm_input to have shape (2, 1) but got array with shape (2, 59173)
Error when checking input: expected lstm_input to have shape (59173, 2) but got array with shape (59173, 1)
Input arrays should have the same number of samples as target arrays. Found 2 input samples and 59173 target samples.
cannot reshape array of size 118346 into shape (39450,2,1)
Error when checking input: expected lstm_input to have shape (59173, 2) but got array with shape (59173, 1)
Error when checking input: expected lstm_input to have shape (59173, 2) but got array with shape (59173, 1)
This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.
This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.
Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [None, 16, 2, 1]
Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [None, 16, 39450, 1]
If a RNN is stateful, it needs to know its batch size. Specify the batch size of your input tensors: 
- If using a Sequential model, specify the batch size by passing a `batch_input_shape` argument to your first layer.
- If using the functional API, specify the batch size by passing a `batch_shape` argument to your Input layer.
Error when checking input: expected lstm_input to have shape (60, 1) but got array with shape (59173, 1)
Error when checking input: expected lstm_input to have shape (60, 59173) but got array with shape (59173, 1)
Error when checking input: expected lstm_input to have shape (1, 59173) but got array with shape (59173, 1)
Input arrays should have the same number of samples as target arrays. Found 2 input samples and 59173 target samples.
cannot reshape array of size 118346 into shape (20,59173,1)
Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: [20, 20]
cannot reshape array of size 118346 into shape (20,2,59173)
Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [20, 20, 2, 59173]
Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (59173, 2)
Error when checking input: expected input_1 to have shape (2, 59173) but got array with shape (59173, 1)
cannot reshape array of size 118346 into shape (2,59173,20)
Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (59173, 2)
The `batch_size` argument value 32 is incompatible with the specified batch size of your Input Layer: 20
 [_Derived_]  Incompatible shapes: [29586,400] vs. [59173,400]
	 [[{{node while_19/body/_1/add}}]]
	 [[sequential/lstm/StatefulPartitionedCall]] [Op:__inference_distributed_function_10906]

Function call stack:
distributed_function -> distributed_function -> distributed_function

 [_Derived_]  Incompatible shapes: [35503,400] vs. [59173,400]
	 [[{{node while_19/body/_1/add}}]]
	 [[sequential/lstm/StatefulPartitionedCall]] [Op:__inference_distributed_function_10906]

Function call stack:
distributed_function -> distributed_function -> distributed_function

 [_Derived_]  Incompatible shapes: [35503,400] vs. [59173,400]
	 [[{{node while_19/body/_1/add}}]]
	 [[sequential/lstm/StatefulPartitionedCall]] [Op:__inference_distributed_function_10906]

Function call stack:
distributed_function -> distributed_function -> distributed_function

 [_Derived_]  Incompatible shapes: [24655,400] vs. [49311,400]
	 [[{{node while_19/body/_1/add}}]]
	 [[sequential/lstm/StatefulPartitionedCall]] [Op:__inference_distributed_function_10906]

Function call stack:
distributed_function -> distributed_function -> distributed_function

 [_Derived_]  Incompatible shapes: [39448,400] vs. [49311,400]
	 [[{{node while_19/body/_1/add}}]]
	 [[sequential/lstm/StatefulPartitionedCall]] [Op:__inference_distributed_function_10906]

Function call stack:
distributed_function -> distributed_function -> distributed_function

In a stateful network, you should only pass inputs with a number of samples that can be divided by the batch size. Found: 49312 samples
The `batch_size` argument value 32 is incompatible with the specified batch size of your Input Layer: 20
The `batch_size` argument value 32 is incompatible with the specified batch size of your Input Layer: 1
Error when checking input: expected input_1 to have shape (1, 2) but got array with shape (2, 1)
In a stateful network, you should only pass inputs with a number of samples that can be divided by the batch size. Found: 49311 samples
Error when checking input: expected input_1 to have shape (1, 1) but got array with shape (1, 2)
Error when checking input: expected lstm_input to have 3 dimensions, but got array with shape (49300, 1)
[Errno 17] File exists: '/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/New_Dataset/High_Low_vs_Prices'
[Errno 2] No such file or directory: '/Users/hu5ky5n0w/Desktop/Crypto/Crypto_Predictor/results/NewData_OriginalModel/HighLowRSI_vs_Prices'
[Errno 2] No such file or directory: 'None/Results.txt'
cannot reshape array of size 236640 into shape (59160,4,32)
Error when checking input: expected lstm_input to have 3 dimensions, but got array with shape (39440, 1)
Error when checking input: expected lstm_input to have 3 dimensions, but got array with shape (49300, 1)
Error when checking input: expected lstm_input to have shape (30, 1) but got array with shape (3, 1)
Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [None, 3, 30, 1]
Error when checking input: expected lstm_input to have shape (30, 1) but got array with shape (1, 3)
Error when checking input: expected lstm_input to have shape (30, 3) but got array with shape (3, 1)
cannot reshape array of size 147900 into shape (49300,30,3)
All layers in a Sequential model should have a single output tensor. For multi-output layers, use the functional API.
All layers in a Sequential model should have a single output tensor. For multi-output layers, use the functional API.
All layers in a Sequential model should have a single output tensor. For multi-output layers, use the functional API.
All layers in a Sequential model should have a single output tensor. For multi-output layers, use the functional API.
All layers in a Sequential model should have a single output tensor. For multi-output layers, use the functional API.
All layers in a Sequential model should have a single output tensor. For multi-output layers, use the functional API.
All layers in a Sequential model should have a single output tensor. For multi-output layers, use the functional API.
All layers in a Sequential model should have a single output tensor. For multi-output layers, use the functional API.
All layers in a Sequential model should have a single output tensor. For multi-output layers, use the functional API.
Error when checking input: expected lstm_input to have 3 dimensions, but got array with shape (49300, 1)
Error when checking input: expected lstm_input to have shape (32, 1) but got array with shape (3, 1)
